version: "3.8"

services:
  frontend:
    image: pixelchat-frontend:latest
    container_name: pixelchat-frontend
    ports:
      - "3000:3000"
    networks:
      - pixelchat-network
  message_api:
    image: pixelchat-message-api:latest
    container_name: pixelchat-message-api
    ports:
      - "3001:3001"
    networks:
      - pixelchat-network
    environment:
      - CASSANDRA_CONTACT_POINTS=pixelchat-cassandra
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
  gateway:
    image: pixelchat-gateway:latest
    container_name: pixelchat-gateway
    ports:
      - "80:80"
    networks:
      - pixelchat-network
    environment:
      - FRONTEND_URL=http://frontend:3000
      - MESSAGE_API_URL=http://message_api:3001
      - USER_SERVICE_URL=http://user_service:3002
      - PORT=80
      - NODE_ENV=production
      - AUTH0_AUDIENCE=pixelchat-gateway-identifier
      - AUTH0_DOMAIN=pixelchat-dev.eu.auth0.com
  user_service:
    image: pixelchat-user-service:latest
    container_name: pixelchat-user-service
    networks:
      - pixelchat-network
    environment:
      - POSTGRES_CONN_STRING=postgres://postgres:epicPassword@pixelchat-postgres:5432/postgres
      - AUTH0_CLIENT_ID=HdJv6Up3hFtaM2Ul1XHWoFJq3mmbZOoJ
      - AUTH0_CLIENT_SECRET=11rWCxSTbBuJAMyF2UtjHsUt1MIirrpB3FdTVjkZVhKRlEt1hhKK4-PURFnyTJps
      - AUTH0_DOMAIN=pixelchat-dev.eu.auth0.com
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    ports:
      - "3002:3002"
  postgres_db:
    image: postgres:13
    container_name: pixelchat-postgres
    networks:
      - pixelchat-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=epicPassword
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cassandra_db:
    image: cassandra:3.11
    container_name: pixelchat-cassandra
    networks:
      - pixelchat-network
    environment:
      - CASSANDRA_CLUSTER_NAME=pixelchatCassandra
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1-pixelchatCassandra
      - CASSANDRA_RACK=Rack1-pixelchatCassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pixelchat-network


networks:
  pixelchat-network:
    name: pixelchat-network
    driver: bridge

volumes:
  postgres_data:
    name: postgres_data
  cassandra_data:
    name: cassandra_data