version: "3.8"

services:
  frontend:
    image: pixelchat-frontend
    container_name: pixelchat-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    # depends_on:
    #   - message_api
  message_api:
    image: pixelchat-message-api
    container_name: pixelchat-message-api
    ports:
      - "3001:3001"
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    # depends_on:
    #   - db