version: "3.8"

services:
  frontend:
    image: pixelchat-frontend
    container_name: pixelchat-frontend
    ports:
      - "3000:3000"
  message_api:
    image: pixelchat-message-api
    container_name: pixelchat-message-api
    ports:
      - "3001:3001"