apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelchat-frontend
  labels:
    app: pixelchat-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixelchat-frontend
  template:
    metadata:
      labels:
        app: pixelchat-frontend
    spec:
      containers:
      - name: pixelchat-frontend
        image: pixelchat-frontend
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 3000
---
# Service for the front-end
# apiVersion: v1
# kind: Service
# metadata:
#   name: pixelchat-frontend
# spec:
#   ports:
#     - name: "3000"
#       port: 3000
#       targetPort: 3000
# status:
#   loadBalancer: {}

apiVersion: v1
kind: Service
metadata:
  name: pixelchat-frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    app: pixelchat-frontend