apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelchat-frontend
  labels:
    app: pixelchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixelchat
  template:
    metadata:
      labels:
        app: pixelchat
    spec:
      containers:
      - name: pixelchat-frontend
        image: pixelchat-frontend
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 3000
---
# backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelchat-message-api
  labels:
    app: pixelchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixelchat
  template:
    metadata:
      labels:
        app: pixelchat
    spec:
      containers:
      - name: pixelchat-message-api
        image: pixelchat-message-api
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: pixelchat-frontend
  labels:
    app: pixelchat
spec:
  selector:
    app: pixelchat
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: pixelchat-message-api
  labels:
    app: pixelchat
spec:
  selector:
    app: pixelchat
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
