apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: pixelchat-frontend
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: pixelchat-frontend
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: pixelchat-gateway
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: pixelchat-gateway
 minReplicas: 1
 maxReplicas: 3
 targetCPUUtilizationPercentage: 75
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: pixelchat-message-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pixelchat-message-api
  minReplicas: 2
  maxReplicas: 7
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: pixelchat-user-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pixelchat-user-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60