apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelchat-message-api
  labels:
    app: pixelchat-message-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixelchat-message-api
  template:
    metadata:
      labels:
        app: pixelchat-message-api
    spec:
      containers:
      - name: pixelchat-message-api
        image: pixelchat-message-api
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 3001
        env:
        # - name: FRONTEND_URL
        #   value: http://pixelchat-frontend:3000
        # - name: MESSAGE_API_URL
        #   value: http://pixelchat-message_api:3001
        - name: PORT
          value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: pixelchat-message-api
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001
    
  selector:
    app: pixelchat-message-api
    