apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelchat-message-api
  labels:
    app: pixelchat-message-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixelchat-message-api
  template:
    metadata:
      labels:
        app: pixelchat-message-api
    spec:
      containers:
      - name: pixelchat-message-api
        image: ghcr.io/teunmos-pixelchat/message-api:develop
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 3001
        env:
        - name: CASSANDRA_CONTACT_POINTS
          value: pixelchat-cassandra-0.pixelchat-cassandra.default.svc.cluster.local,pixelchat-cassandra-1.pixelchat-cassandra.default.svc.cluster.local,pixelchat-cassandra-2.pixelchat-cassandra.default.svc.cluster.local
        - name: RABBITMQ_HOST
          value: pixelchat-rabbitmq
        - name: RABBITMQ_USER
          value: guest
        - name: RABBITMQ_PASS
          value: guest
      imagePullSecrets:
      - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: pixelchat-message-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  selector:
    app: pixelchat-message-api