# https://stackgres.io/
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: pixelchat-postgres-stackgres-cluster
spec:
  configurations:
    credentials:
      users:
        superuser:
          username:
            name: postgres-credentials
            key: username
          password:
            name: postgres-credentials
            key: password
  instances: 2
  postgres:
    version: 'latest'
  pods:
    persistentVolume:
      size: '5Gi'
  autoscaling:
    minInstances: 2
    maxInstances: 4
    maxAllowed:
      envoy:
        cpu: 1500m
        memory: 1Gi
      patroni:
        cpu: 1500m
        memory: 1Gi
      pgbouncer:
        cpu: 1500m 
        memory: 1Gi
    minAllowed:
      envoy:
        cpu: 100m
        memory: 100Mi
      patroni:
        cpu: 100m
        memory: 100Mi
      pgbouncer:
        cpu: 100m
        memory: 100Mi