apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: cG9zdGdyZXM=  # Base64 encoded 'postgres'
  password: ZXBpY1Bhc3N3b3Jk
# ---

# Path: kubernetes/user-service.yaml

