apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: cG9zdGdyZXM=  # Base64 encoded 'postgres'
  password: ZXBpY1Bhc3N3b3Jk
---
apiVersion: v1
kind: Secret
metadata:
  name: pixelchat-auth0-secret
data:
  AUTH0_CLIENT_ID: __
  AUTH0_CLIENT_SECRET: __
  AUTH0_DOMAIN: __
  
---
apiVersion: v1
kind: Secret
metadata:
  name: pixelchat-user-service-secret
data:
  POSTGRES_CONN_STRING: __
