apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelchat-user-service
  labels:
    app: pixelchat-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixelchat-user-service
  template:
    metadata:
      labels:
        app: pixelchat-user-service
    spec:
      containers:
      - name: pixelchat-user-service
        image: ghcr.io/teunmos-pixelchat/user-service:develop
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 350m
            memory: 512Mi
        ports:
        - containerPort: 3002
        env:
        - name: POSTGRES_CONN_STRING
          valueFrom:
            secretKeyRef:
              name: pixelchat-user-service-secret
              key: POSTGRES_CONN_STRING
        - name: AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: pixelchat-auth0-secret
              key: AUTH0_CLIENT_ID
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: pixelchat-auth0-secret
              key: AUTH0_CLIENT_SECRET
        - name: AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              name: pixelchat-auth0-secret
              key: AUTH0_DOMAIN
      imagePullSecrets:
      - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: pixelchat-user-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3002
    targetPort: 3002
  selector:
    app: pixelchat-user-service